services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    shm_size: 2gb
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "4444:4444"
