---
name: Markdown Lint

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  packages: read
  statuses: write

  jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: '**/*.md'